<?php

namespace Modules\User\Database;

use Illuminate\Database\Seeder;
use Modules\Product\Models\Category;
use Modules\Product\Models\Product;
use Modules\Product\Models\ProductVariation;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $products = array(
            array(
                "id" => 1,
                "category_id" => 1,
                "name" => "Calabresa",
                "notes" => "- molho\n- muçarela\n- calabresa\n- cebola\n- orégano",
            ),
            array(
                "id" => 2,
                "category_id" => 1,
                "name" => "Frango",
                "notes" => "- molho\n- muçarela\n- frango\n- milho\n- orégano",
            ),
            array(
                "id" => 3,
                "category_id" => 1,
                "name" => "Presunto",
                "notes" => "- molho\n- muçarela\n- presunto\n- orégano",
            ),
            array(
                "id" => 4,
                "category_id" => 1,
                "name" => "Mista",
                "notes" => "- molho\n- muçarela\n- frango\n- calabresa\n- presunto\n- orégano",
            ),
            array(
                "id" => 5,
                "category_id" => 2,
                "name" => "Muçarela",
                "notes" => "- muçarela\n- tomate\n- azeitona\n- orégano",
            ),
            array(
                "id" => 6,
                "category_id" => 2,
                "name" => "Calabresa",
                "notes" => "- muçarela\n- calabresa\n- azeitona\n- orégano\n- cebola",
            ),
            array(
                "id" => 7,
                "category_id" => 2,
                "name" => "Presunto",
                "notes" => "- muçarela\n- presunto\n- azeitona\n- orégano",
            ),
            array(
                "id" => 8,
                "category_id" => 2,
                "name" => "Bacon",
                "notes" => "- muçarela\n- bacon\n- azeitona\n- orégano",
            ),
            array(
                "id" => 9,
                "category_id" => 2,
                "name" => "Bambina",
                "notes" => "- muçarela\n- presunto\n- frango\n- milho\n- ervilha\n- azeitona\n- orégano",
            ),
            array(
                "id" => 10,
                "category_id" => 2,
                "name" => "Napolitana",
                "notes" => "- muçarela\n- requeijão\n- tomate\n- azeitona\n- orégano",
            ),
            array(
                "id" => 11,
                "category_id" => 2,
                "name" => "Itália",
                "notes" => "- muçarela\n- presunto\n- calabresa\n- azeitona\n- orégano",
            ),
            array(
                "id" => 12,
                "category_id" => 2,
                "name" => "Siliciana",
                "notes" => "- muçarela\n- calabresa\n- bacon\n- azeitona\n- orégano",
            ),
            array(
                "id" => 13,
                "category_id" => 2,
                "name" => "Marguerita",
                "notes" => "- muçarela\n- tomate\n- manjericão\n- azeitona\n- orégano",
            ),
            array(
                "id" => 14,
                "category_id" => 3,
                "name" => "À Moda",
                "notes" => NULL,
            ),
            array(
                "id" => 15,
                "category_id" => 3,
                "name" => "Mexicana",
                "notes" => NULL,
            ),
            array(
                "id" => 16,
                "category_id" => 3,
                "name" => "Balacubana",
                "notes" => NULL,
            ),
            array(
                "id" => 17,
                "category_id" => 3,
                "name" => "Nordestina",
                "notes" => NULL,
            ),
            array(
                "id" => 18,
                "category_id" => 3,
                "name" => "Carijó",
                "notes" => NULL,
            ),
            array(
                "id" => 19,
                "category_id" => 3,
                "name" => "4 Queijos",
                "notes" => NULL,
            ),
            array(
                "id" => 20,
                "category_id" => 3,
                "name" => "Portuguesa",
                "notes" => NULL,
            ),
            array(
                "id" => 21,
                "category_id" => 3,
                "name" => "Romanesca",
                "notes" => NULL,
            ),
            array(
                "id" => 22,
                "category_id" => 3,
                "name" => "Seis cobertas",
                "notes" => NULL,
            ),
            array(
                "id" => 23,
                "category_id" => 3,
                "name" => "Paulista",
                "notes" => NULL,
            ),
            array(
                "id" => 24,
                "category_id" => 3,
                "name" => "Baiana",
                "notes" => NULL,
            ),
            array(
                "id" => 25,
                "category_id" => 5,
                "name" => "Tamarindo",
                "notes" => NULL,
            ),
            array(
                "id" => 26,
                "category_id" => 5,
                "name" => "Graviola",
                "notes" => NULL,
            ),
            array(
                "id" => 27,
                "category_id" => 5,
                "name" => "Bacuri",
                "notes" => NULL,
            ),
            array(
                "id" => 28,
                "category_id" => 5,
                "name" => "Abacaxi",
                "notes" => NULL,
            ),
            array(
                "id" => 29,
                "category_id" => 5,
                "name" => "Cajú",
                "notes" => NULL,
            ),
            array(
                "id" => 30,
                "category_id" => 5,
                "name" => "Goiaba",
                "notes" => NULL,
            ),
            array(
                "id" => 31,
                "category_id" => 5,
                "name" => "Maracujá",
                "notes" => NULL,
            ),
            array(
                "id" => 32,
                "category_id" => 5,
                "name" => "Acerola",
                "notes" => NULL,
            ),
            array(
                "id" => 33,
                "category_id" => 5,
                "name" => "Cupuaçu",
                "notes" => NULL,
            ),
            array(
                "id" => 34,
                "category_id" => 5,
                "name" => "Cajá",
                "notes" => NULL,
            ),
            array(
                "id" => 35,
                "category_id" => 6,
                "name" => "Skol",
                "notes" => NULL,
            ),
            array(
                "id" => 36,
                "category_id" => 6,
                "name" => "Bohemia",
                "notes" => NULL,
            ),
            array(
                "id" => 37,
                "category_id" => 6,
                "name" => "Antártica",
                "notes" => NULL,
            ),
            array(
                "id" => 38,
                "category_id" => 6,
                "name" => "Brahma",
                "notes" => NULL,
            ),
            array(
                "id" => 39,
                "category_id" => 6,
                "name" => "Devassa",
                "notes" => NULL,
            ),
            array(
                "id" => 40,
                "category_id" => 4,
                "name" => "Cajuína",
                "notes" => NULL,
            ),
            array(
                "id" => 41,
                "category_id" => 4,
                "name" => "Água mineral",
                "notes" => NULL,
            ),
            array(
                "id" => 42,
                "category_id" => 7,
                "name" => "Refrigerante",
                "notes" => NULL,
            ),
        );

        foreach ($products as $item) {

            Product::create($item);

        }

        $product_variations = array(
            array(
                "id" => 1,
                "product_id" => 1,
                "name" => "G",
                "price" => 14.00,
                "available" => 1,
            ),
            array(
                "id" => 2,
                "product_id" => 2,
                "name" => "G",
                "price" => 14.00,
                "available" => 1,
            ),
            array(
                "id" => 3,
                "product_id" => 3,
                "name" => "G",
                "price" => 14.00,
                "available" => 1,
            ),
            array(
                "id" => 4,
                "product_id" => 4,
                "name" => "G",
                "price" => 14.00,
                "available" => 1,
            ),
            array(
                "id" => 5,
                "product_id" => 5,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 6,
                "product_id" => 5,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 7,
                "product_id" => 5,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 8,
                "product_id" => 5,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 9,
                "product_id" => 6,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 10,
                "product_id" => 6,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 11,
                "product_id" => 6,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 12,
                "product_id" => 6,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 13,
                "product_id" => 7,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 14,
                "product_id" => 7,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 15,
                "product_id" => 7,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 16,
                "product_id" => 7,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 17,
                "product_id" => 8,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 18,
                "product_id" => 8,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 19,
                "product_id" => 8,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 20,
                "product_id" => 8,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 21,
                "product_id" => 9,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 22,
                "product_id" => 9,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 23,
                "product_id" => 9,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 24,
                "product_id" => 9,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 25,
                "product_id" => 10,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 26,
                "product_id" => 10,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 27,
                "product_id" => 10,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 28,
                "product_id" => 10,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 29,
                "product_id" => 11,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 30,
                "product_id" => 11,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 31,
                "product_id" => 11,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 32,
                "product_id" => 11,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 33,
                "product_id" => 12,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 34,
                "product_id" => 12,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 35,
                "product_id" => 12,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 36,
                "product_id" => 12,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 37,
                "product_id" => 13,
                "name" => "P",
                "price" => 20.00,
                "available" => 1,
            ),
            array(
                "id" => 38,
                "product_id" => 13,
                "name" => "M",
                "price" => 25.00,
                "available" => 1,
            ),
            array(
                "id" => 39,
                "product_id" => 13,
                "name" => "G",
                "price" => 32.00,
                "available" => 1,
            ),
            array(
                "id" => 40,
                "product_id" => 13,
                "name" => "GG",
                "price" => 40.00,
                "available" => 1,
            ),
            array(
                "id" => 41,
                "product_id" => 14,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 42,
                "product_id" => 14,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 43,
                "product_id" => 14,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 44,
                "product_id" => 14,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 45,
                "product_id" => 15,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 46,
                "product_id" => 15,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 47,
                "product_id" => 15,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 48,
                "product_id" => 15,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 49,
                "product_id" => 16,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 50,
                "product_id" => 16,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 51,
                "product_id" => 16,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 52,
                "product_id" => 16,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 53,
                "product_id" => 17,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 54,
                "product_id" => 17,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 55,
                "product_id" => 17,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 56,
                "product_id" => 17,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 57,
                "product_id" => 18,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 58,
                "product_id" => 18,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 59,
                "product_id" => 18,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 60,
                "product_id" => 18,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 61,
                "product_id" => 19,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 62,
                "product_id" => 19,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 63,
                "product_id" => 19,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 64,
                "product_id" => 19,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 65,
                "product_id" => 20,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 66,
                "product_id" => 20,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 67,
                "product_id" => 20,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 68,
                "product_id" => 20,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 69,
                "product_id" => 21,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 70,
                "product_id" => 21,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 71,
                "product_id" => 21,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 72,
                "product_id" => 21,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 73,
                "product_id" => 22,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 74,
                "product_id" => 22,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 75,
                "product_id" => 22,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 76,
                "product_id" => 22,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 77,
                "product_id" => 23,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 78,
                "product_id" => 23,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 79,
                "product_id" => 23,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 80,
                "product_id" => 23,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 81,
                "product_id" => 24,
                "name" => "P",
                "price" => 22.00,
                "available" => 1,
            ),
            array(
                "id" => 82,
                "product_id" => 24,
                "name" => "M",
                "price" => 27.00,
                "available" => 1,
            ),
            array(
                "id" => 83,
                "product_id" => 24,
                "name" => "G",
                "price" => 34.00,
                "available" => 1,
            ),
            array(
                "id" => 84,
                "product_id" => 24,
                "name" => "GG",
                "price" => 42.00,
                "available" => 1,
            ),
            array(
                "id" => 85,
                "product_id" => 25,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 86,
                "product_id" => 26,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 87,
                "product_id" => 27,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 88,
                "product_id" => 28,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 89,
                "product_id" => 29,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 90,
                "product_id" => 30,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 91,
                "product_id" => 31,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 92,
                "product_id" => 32,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 93,
                "product_id" => 33,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 94,
                "product_id" => 34,
                "name" => "500 ml",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 95,
                "product_id" => 35,
                "name" => "600 ml",
                "price" => 7.00,
                "available" => 1,
            ),
            array(
                "id" => 96,
                "product_id" => 36,
                "name" => "600 ml",
                "price" => 7.00,
                "available" => 1,
            ),
            array(
                "id" => 97,
                "product_id" => 37,
                "name" => "600 ml",
                "price" => 7.00,
                "available" => 1,
            ),
            array(
                "id" => 98,
                "product_id" => 38,
                "name" => "600 ml",
                "price" => 7.00,
                "available" => 1,
            ),
            array(
                "id" => 99,
                "product_id" => 39,
                "name" => "600 ml",
                "price" => 7.00,
                "available" => 1,
            ),
            array(
                "id" => 100,
                "product_id" => 40,
                "name" => "Cajuína",
                "price" => 7.00,
                "available" => 1,
            ),
            array(
                "id" => 101,
                "product_id" => 41,
                "name" => "Com gás",
                "price" => 3.00,
                "available" => 1,
            ),
            array(
                "id" => 102,
                "product_id" => 41,
                "name" => "Sem gás",
                "price" => 2.00,
                "available" => 1,
            ),
            array(
                "id" => 103,
                "product_id" => 42,
                "name" => "Coca KS 290 ml",
                "price" => 3.00,
                "available" => 1,
            ),
            array(
                "id" => 104,
                "product_id" => 42,
                "name" => "1L",
                "price" => 5.00,
                "available" => 1,
            ),
            array(
                "id" => 105,
                "product_id" => 42,
                "name" => "Lata",
                "price" => 3.50,
                "available" => 1,
            ),
        );

        foreach ($product_variations as $item) {

            ProductVariation::create($item);

        }


    }
}
